services:
  - type: web
    name: telegram-rename-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: bash -lc 'python3 bot.py & gunicorn app:app -b 0.0.0.0:$PORT'
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: DATABASE_NAME
        sync: false
      - key: LOG_CHANNEL
        sync: false
      - key: FORCE_SUBS
        sync: false
      - key: STRING_SESSION
        sync: false
      - key: START_PIC
        sync: false
      - key: SHORTNER_URL
        sync: false
      - key: SHORTNER_API
        sync: false
      - key: TOKEN_TIMEOUT
        sync: false
    autoDeploy: false
