
services:
  - type: web
    name: telegram-rename-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 bot.py
    plan: free
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN
        sync: false
      - key: LOG_CHANNEL
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: DATABASE_NAME
        value: JishuBotz
      - key: START_PIC
        value: https://graph.org/file/ad48ac09b1e6f30d2dae4.jpg
      - key: STRING_SESSION
        sync: false
      - key: FORCE_SUBS
        sync: false
      - key: PORT
        value: 5000
    healthCheckPath: /health
